name: Verify

on: push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        timezone: [UTC, CET, Europe/Brussels, Asia/Shanghai]
    env:
      TZ: ${{ matrix.timezone }}
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js
      uses: actions/setup-node@main
    - name: npm ci
      run: npm ci
    - name: npm run verify
      run: |
        echo "Verifying in timezone '$TZ'"
        npm run verify
